name: smartship_partner
description: SmartShip Partner

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+23

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^5.0.1
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  firebase_analytics: ^8.3.1
  firebase_messaging: ^10.0.6
  firebase_remote_config: ^0.10.0+2
  firebase_crashlytics: ^2.2.1
  fluttertoast: ^8.0.8

  google_maps_flutter: ^2.0.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_map_polyline:
    git:
      url: https://github.com/plitto007/google_map_polyline.git
      ref: master
  permission: ^0.1.7

  retrofit: 2.0.1
  logger: any

  flutter_screenutil: ^2.3.1
  fluro: ^2.0.3
  shared_preferences: ^2.0.7
  connectivity: ^3.0.6
  equatable: ^1.2.2
  intl: ^0.17.0
  country_code_picker: ^2.0.2
  otp_text_field: ^1.0.1
  package_info: ^0.4.1

  json_annotation: ^4.0.1
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.9
  flutter_rating_bar: ^3.0.1+1
  modal_progress_hud: ^0.1.3
  event_bus: ^1.1.1
  popup_menu: ^1.0.5
  roundcheckbox: ^1.0.0+1
  pedantic: ^1.0.0
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1
  pull_to_refresh: ^2.0.0
  wc_flutter_share: ^0.4.0
  uuid: 3.0.4
  async: ^2.6.1
  photo_view: ^0.10.2
  carousel_slider: ^2.3.1

  floor: ^1.1.0 #database
  image_picker: 0.8.3+3
  cached_network_image: ^2.2.0+1

  flutter_local_notifications: ^8.1.1
  tiengviet: ^0.4.1
  visibility_detector: ^0.1.5
  flutter_statusbarcolor_ns: ^0.4.0
  lazy_load_scrollview: ^1.1.0
  focus_detector: ^1.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.1
  build_runner: ^2.1.1
  json_serializable: ^4.1.2
  flutter_launcher_icons: ^0.9.2  #generate icon: flutter pub run flutter_launcher_icons:main
  floor_generator: ^1.1.0 #database
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
dependency_overrides:
  modal_bottom_sheet: ^2.0.0
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher/icon.png"
  image_path_android: "assets/images/launcher/icon.png"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/phone/
    - assets/locale/
    - assets/configs/
  #    - assets/images/phone/im_splash.png
  #    - assets/images/phone/im_splash_icon.png
  #    - assets/images/phone/ic_edit.svg
  #    - assets/images/phone/ic_statistic.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.ttf
        - asset: assets/fonts/Futura-Bold.ttf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
